#!/usr/bin/env bash

# -e exit if command fails
# -u treat unset variable as error, 
# -x print commands and theri arguments as they are executed
set -eux

CONFIG=$HOME/.config
SRC=src

# Read the command -> { install, sync, help }
echo -e "install -> Install the file\nsync -> sync current repo with .config files\nhelp -> show this help"
read command
files=(kitty nvim tmux zathura zsh)

if [[ "$command" == "help" ]] || [[ "$command" == "" ]]; then
	echo -e "install, sync, help"
elif [[ "$command" == "install" ]]; then
	# Copy of the current configuratio
	mkdir backup
	for file in "${files[@]}"; do
		if [ -e $CONFIG/$file ]; then
			mv $CONFIG/$file backup
		fi
	done
	
	# Install new config
	for file in "${files[@]}"; do
		mv $SRC/$file $CONFIG
	done
	
	# ZSH related
	mv $SRC/zshenv $HOME/.zshenv
	mv $CONFIG/zsh/zshrc $CONFIG/zsh/.zshrc

elif [[ "$command" == "sync" ]]; then
	# Copy config file from .config
	for file in "${files[@]}"; do
		if [ -e $CONFIG/$file ]; then
			cp -r $CONFIG/$file $SRC
		fi
	done

	cp $HOME/.zshenv $SRC/zshenv
	mv $SRC/zsh/.zshrc $SRC/zsh/zshrc
else
	echo "Invalid command ==> $command"
fi
