#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd >~/Desktop/debug &

feh --bg-scale $HOME/.config/bspwm/pics/wp.jpg
setxkbmap it

bspc monitor -d I II III IV V

bspc config border_width 3
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Colors
bspc config normal_border_color '#525252'
bspc config active_border_color '#525252'
bspc config focused_border_color '#be95ff'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
