#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
feh --bg-scale $HOME/.config/bspwm/pics/wp.jpg
picom &
$HOME/.config/lemonbar/lemonscript &
clipse -listen
dunst -startup_notification &

bspc monitor -d 1 2 3 4 5

bspc config border_width 3
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Colors
bspc config normal_border_color '#202020'
bspc config active_border_color '#202020'
bspc config focused_border_color '#f07178'

# Rules
bspc rule -a clipse state=floating center=on focus=on rectangle=1440x900+730+450
bspc rule -a feh state=floating center=on focus=on rectangle=1440x900+730+450
