# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12.0

# Theme
include themes/mocha.conf
set termguicolors

# Scroll
scrollback_lines 2000 
scrollback_fill_enlarged_window yes 

# Mouse
mouse_hide_wait 1.0

# Performance
sync_to_monitor yes

# Terminal Bell
enable_audio_bell no

# Windows Layout
window_padding_width 5
background_opacity 1
